---
title: "Modelado"
subtitle: "Pre-procesamiento, análisis exploratorio y modelado de datos"
author: "Raya Castillo, José Raúl"
date: last-modified
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Índice"
    number-sections: true
    embed-resources: true
    self-contained-math: true
    code-fold: true
    code-copy: true
    code-overflow: wrap
    theme: cosmo
knitr:
  opts_knit:
    root.dir: ".."
bibliography: references.bib
---

# Introducción

El flujo de trabajo seguido para el preprocesamiento de datos es:

```{mermaid}

```

# Pre-procesamiento

## Normalización

```{r}
# 1. Carga de paquetes y limpieza de entorno
# 1.1. Limpiamos la RAM
rm(list = ls(globalenv()))
pacman::p_unload(pacman::p_loaded(), character.only = TRUE)
base::gc(full = TRUE)

# 1.2. Cargamos las librerías a emplear
pacman::p_load(terra, sf, dplyr, here)

# 1.3. Configuración de directorios temporales de 'terra'
terra::terraOptions(
  tempdir = here::here("temp/temp_terra"),
  todisk  = TRUE
)

# 2. Crear datasets de variables a normalizar
# 2.1. Presencias 
# 2.1.1. 'Bounding box' del área de estudio
roi <- sf::st_read(
  here::here("data/variables/variables_geograficas/carreteras/carreteras_buffer_25.gpkg"),
  quiet = TRUE
) %>% 
  sf::st_transform("EPSG:25830")

# 2.1.2. Rásteres binarios (0, 1) de píxeles invadidos (o no) en un periodo dado
diferencia_2008_2012 <- here::here("data/presencias/diferencia_2008_2012_rast.tif")

diferencia_2008_2023 <- here::here("data/presencias/diferencia_2008_2023_rast.tif")

diferencia_2014_2023 <- here::here("data/presencias/diferencia_2014_2023_rast.tif")

diferencia_2018_2023 <- here::here("data/presencias/diferencia_2018_2023_rast.tif")

diferencia_2020_2023 <- here::here("data/presencias/diferencia_2020_2023_rast.tif")

# 2.2. Variables predictoras
# 2.2.1. Variables bióticas
# 2.2.1.1. Variables funcionales (índices de vegetación)
variables_funcionales_2008_2012 <- list(
  here::here("data/variables/variables_bioticas/funcional/rgb/orto_2007/orto_2007_vi.tif")
)

variables_funcionales_2008_2023 <- list(
  here::here("data/variables/variables_bioticas/funcional/rgb/orto_2007/orto_2007_vi.tif")
)

variables_funcionales_2018_2023 <- list.files(
  path = here::here("data/variables/variables_bioticas/funcional/sentinel/2018_2024"),
  pattern = "\\.tif$",
  full.names = TRUE,
  recursive = TRUE
)

variables_funcionales_2020_2023 <- list.files(
  path = here::here("data/variables/variables_bioticas/funcional/sentinel/2018_2024"),
  pattern = "\\.tif$",
  full.names = TRUE,
  recursive = TRUE
)

# variables_funcionales_2014_2023 <- list(
#     list.files(
#     path = here::here("data/variables/variables_bioticas/funcional/sentinel"),
#     pattern = "\\.tif$",
#     full.names = TRUE,
#     recursive = TRUE
#   ),
#   here::here("data/variables/variables_bioticas/funcional/rgb/orto_2007/orto_2013_vi.tif")
# )

# 2.2.1.2. Variables estructurales (métricas derivadas de datos LiDAR)
variables_estructurales_2014_2023 <- list.files(
  path = here::here("data/variables/variables_bioticas/estructural/"),
  pattern = "\\.tif$",
  full.names = TRUE,
  recursive = TRUE
)

variables_estructurales_2020_2023 <- list.files(
  path = here::here("data/variables/variables_bioticas/estructural/"),
  pattern = "\\.tif$",
  full.names = TRUE,
  recursive = TRUE
)

# 2.2.1.3. Distancia a focos de invasión (presencias)
distancia_focos_

# 2.3. Variables antrópicas
variables_geograficas <- list(
  list.files(
    path = here::here("data/variables/variables_geograficas"),
    pattern = "(cauces|nucleos)_distancia_5\\.tif$", 
    full.names = TRUE,
    recursive = TRUE
  ),
  here::here("data/presencias/ailanto_2008.tif"),
  here::here("data/variables/variables_geograficas/hfp/hfp.tif"),
  here::here("data/variables/variables_geograficas/mucva/mucva_2007.tif"),
  here::here("data/variables/variables_geograficas/landcover/landcover_2006.tif")
)

# 2.4. Variables del relieve
variables_relieve <- list(
  c(
    here::here("data/variables/variables_relieve/radiacion/radiacion_directa.tif"),
    here::here("data/variables/variables_relieve/mde/mde.tif"),
    here::here("data/variables/variables_relieve/slope/slope_grados.tif"),
    here::here("data/variables/variables_relieve/slope/downslope_index.tif"),
    here::here("data/variables/variables_relieve/twi/sca.tif"),
    here::here("data/variables/variables_relieve/twi/twid.tif"),
    here::here("data/variables/variables_relieve/twi/twi.tif"),
    here::here("data/variables/variables_relieve/tpi/tpi.tif"),
    here::here("data/variables/variables_relieve/tri/tri.tif"),
    here::here("data/variables/variables_relieve/aspect/aspect.tif")
  )
)

# 2.5. Datasets de variables a normalizar
lista_2008_2012 <- unlist( # Aplanar lista
  list(
    diferencia_2008_2012, 
    variables_funcionales_2008_2012, 
    variables_geograficas, 
    variables_relieve
  )
)

lista_2008_2023 <- unlist( 
  list(
    diferencia_2008_2023, 
    variables_funcionales_2008_2023, 
    variables_geograficas, 
    variables_relieve
  )
)

# lista_2014_2023 <- unlist(
#   list(
#     presencias_2014_2023, 
#     variables_funcionales_2014_2023, 
#     variables_estructurales, 
#     variables_geograficas, 
#     variables_relieve
#   )
# )

# 3. Creamos la función de normalización de las varibales
normalizacion <- function(lista, ruta, temp, aoi) {
  # 1. Cargar plantilla raster
  plantilla <- lista[[1]] %>% 
    terra::rast() %>%
    terra::project(
      "EPSG:25830", 
      method = "near"
    )

  # 2. Crear vector de rutas finales
  rutas_tmp <- character(length(lista))

  # 3. Bucle de procesado de las variables
  for (i in seq_along(lista)) {
    cat("Procesando", i, "de", length(lista), ":", basename(lista[[i]]), "\n")

    # 3.1. Reproyección
    terra::rast(lista[[i]]) %>%
      terra::project(
        y = "EPSG:25830", 
        method = "near",
        filename = file.path(temp, paste0("tmp_", i, "_proj.tif")),
        overwrite = TRUE, 
        gdal = c("BIGTIFF=YES", "COMPRESS=LZW", "TILED=YES"),
        threads = TRUE
      ) 

    # 3.2. Remuestreo
    file.path(temp, paste0("tmp_", i, "_proj.tif")) %>% 
      terra::rast() %>%
      terra::resample(
        y = plantilla,
        filename = file.path(temp, paste0("tmp_", i, "_res.tif")), 
        overwrite = TRUE, 
        gdal = c("BIGTIFF=YES", "COMPRESS=LZW", "TILED=YES"),
        threads = TRUE
      ) 

    file.remove(
      file.path(temp, paste0("tmp_", i, "_proj.tif"))
    )

    # 3.3. Recorte y enmascarado
    r_final <- file.path(temp, paste0("tmp_", i, "_res.tif")) %>% 
      terra::rast() %>%
      terra::crop(aoi) %>%
      terra::mask(aoi)

    file.remove(
      file.path(temp, paste0("tmp_", i, "_res.tif"))
    )

    # 3.4. Asignación de nombres
    # 3.4.1. Generar vector con el (/los) nombre(s)
    nombres <- if (terra::nlyr(r_final) == 1) {
      tools::file_path_sans_ext(basename(lista[[i]]))
    } else {
      paste0(
        tools::file_path_sans_ext(basename(lista[[i]])), "_", seq_len(terra::nlyr(r_final))
      )
    }

    # 3.4.2. Asignar el (/los) nombre(s)
    terra::set.names(
      r_final, 
      nombres
    )

    # 3.5. Guardado del temporal
    terra::writeRaster(
      r_final, 
      file.path(temp, paste0("tmp_", i, ".tif")), 
      overwrite = TRUE, 
      gdal = c("BIGTIFF=YES", "COMPRESS=LZW", "TILED=YES")
    )
    
    rutas_tmp[i] <- file.path(temp, paste0("tmp_", i, ".tif"))

    rm(nombres, r_final)
    gc(full = TRUE)
  }

  # 4. Generar raster multibanda final
  rutas_tmp %>% 
    terra::rast() %>%
    terra::writeRaster(
      ruta, 
      overwrite = TRUE, 
      gdal = c("BIGTIFF=YES", "COMPRESS=LZW", "TILED=YES")
    )

  # 5. Limpiar temporales
  file.remove(rutas_tmp)
  gc(full = TRUE)
}

# 4. Crear stacks de variables normalizadas
variables_2008_2012 <- normalizacion(
  lista = lista_2008_2012,
  ruta = here::here("data/modelos/normalizacion/variables_2008_2012.tif"),
  temp = here::here("temp/temp_terra"),
  aoi = roi
)

variables_2008_2023 <- normalizacion(
  lista = lista_2008_2023,
  ruta = here::here("data/modelos/normalizacion/variables_2008_2023.tif"),
  temp = here::here("temp/temp_terra"),
  aoi = roi
)

# variables_2014_2023 <- normalizacion(
#   lista = lista_2014_2023,
#   ruta = here::here("data/modelos/normalizacion/variables_2014_2023.tif")
# )

terra::tmpFiles(current = TRUE, orphan = TRUE, old = TRUE, remove = TRUE)
```

## Balanceo

```{r}
# 1. Carga de paquetes y limpieza de entorno
# 1.1. Limpiamos la RAM
rm(list = ls(all.names = TRUE))
pacman::p_unload(pacman::p_loaded(), character.only = TRUE)
gc(full = TRUE)
terra::tmpFiles(remove = TRUE)

# 1.2. Cargamos las librerías a emplear
pacman::p_load(terra, sf, dplyr, tidyr, purrr, here)

# 2. Carga de datos
lista <- lapply(
  X = list(
    diferencia_2008_2012 = here::here("data/modelos/normalizacion/variables_2008_2012.tif"),
    diferencia_2008_2023 = here::here("data/modelos/normalizacion/variables_2008_2023.tif")
  ),
  FUN = terra::rast
)

# 3. Balanceo del dataframe de variables
# 3.1. Crear función de balanceo
balanceo <- function(stack) {
  # 1. Establecer semilla 
  set.seed(123)
  
  # 2. Convertir a dataframe y limpiar valores no finitos
  df <- terra::as.data.frame(stack, na.rm = TRUE) %>% 
    dplyr::filter(if_all(everything(), is.finite))
  
  # 3. Identificar variable respuesta
  target_var <- names(df)[grep("^diferencia_", names(df))][1]
  
  # 4. Calculo del grupo más pequeño
  min_size <- df %>%
    dplyr::group_by(across(all_of(target_var))) %>%
    dplyr::tally() %>%
    dplyr::pull(n) %>%
    min()

  # 5. Balanceo y factorización
  df_bal <- df %>%
    dplyr::group_by(across(all_of(target_var))) %>%
    dplyr::slice_sample(n = min_size) %>% # Usamos la constante calculada
    dplyr::ungroup() %>%
    dplyr::mutate(across(all_of(target_var), ~ {
      f <- as.factor(.x)
      levels(f) <- c("Ausente", "Presente") 
      return(f)
    }))
  
  # 6. Comprobación
  print(table(df_bal[[target_var]]))
  
  # 7. Salida de la función
  return(as.data.frame(df_bal))
}

# 3.2. Aplicar función de balanceo
lista_balanceo <- lapply(
  X = lista,
  FUN = balanceo
)

# 4. Guardado
saveRDS(
  lista_balanceo[[1]],
  here::here("data/modelos/balanceo/df_balanceo_2008_2012.RDS")
)

saveRDS(
  lista_balanceo[[2]],
  here::here("data/modelos/balanceo/df_balanceo_2008_2023.RDS")
)
```

## Escalado

```{r}
# 1. Carga de paquetes y limpieza de entorno
# 1.1. Limpiamos la RAM
rm(list = ls(all.names = TRUE))
pacman::p_unload(pacman::p_loaded(), character.only = TRUE)
gc(full = TRUE)
# terra::tmpFiles(remove = TRUE)

# 1.2. Cargamos las librerías a emplear
pacman::p_load(terra, sf, dplyr, tidyr, purrr, here)

# 2. Carga de datos
lista <- lapply(
  X = list(
    diferencia_2008_2012 = here::here("data/modelos/balanceo/df_balanceo_2008_2012.RDS"),
    diferencia_2008_2023 = here::here("data/modelos/balanceo/df_balanceo_2008_2023.RDS")
  ),
  FUN = base::readRDS
)

# 3. Escalado de variables
# 3.1. Crear función de escalado
escalado <- function(dataframe) {
  # 1. Identificar variables categóricas
  categoricas <- names(dataframe)[grep("^diferencia_|landcover_|mucva_", names(dataframe))]

  # 2. Escalado y filtrado de variables categóricas
  dataframe_escalado <- dataframe %>%
    dplyr::mutate(across(dplyr::all_of(categoricas), as.factor)) %>% 
    dplyr::select(where(is.numeric)) %>% # Eliminar variables categóricas
    base::scale()

  # 3. Salida de la función
  return(dataframe_escalado)
}

# 3.2. Aplicar función de escalado
lista_escalado <- lapply(
  X = lista,
  FUN = escalado
)

# 4. Guardado
saveRDS(
  lista_escalado[[1]],
  here::here("data/modelos/escalado/df_escalado_2008_2012.RDS")
)

saveRDS(
  lista_escalado[[2]],
  here::here("data/modelos/escalado/df_escalado_2008_2023.RDS")
)
```

## Filtrado